### PR TITLE
Fixing issues with the Algolia overquota

### PR DESCRIPTION
**Pull request by pixelastic**
Here is the follow-up to #3 

I updated the jekyll-algolia plugin to the new version. I added more tests on my side to make sure records stay under the 10Kb limit (or at least having a clear indication of which record fails and why). I reverted to your application id, and you should be able to run the indexing with your own account now.

I had to edit a few of your blog posts. I think some of them were extracted from a Wordpress instance and the markup was adding `<p>` around large chunks of code (and because `<p>` are indexed by the plugin, it resulted in records too large to be indexed). I also had to rename an `.html` file to `.md` (seems like it was a an error).

Let me know how it goes this time :)

I'm going to submit another PR for the jumping titles.

### CODE REVIEW

**Comment by tomjoht** [comment]
Awesome. Thanks. Yes, previously my blog was on WordPress, and the migration converted a lot of posts like that. At some point I'd like to go back in and clean them up, but I just haven't yet. Thanks for fixing them.

**Comment by tomjoht** [comment]
Sweet. Thanks for updating the plugin. I ran the index again on all 3 sites and didn't run into any size issues. Also, thanks for fixing the jump issue with the display. I see you added code for the learnapidoc and simplifying-complexity sites that fixed it. But with idratherbewriting, I didn't see the same styles added (prob b/c the search integration is different), so I just copied a snippet from the other updates:

```
#search-hits-wrapper {
  display: none;
}
```
This fixed the jumpiness on idratherbewriting.

The search box was a little big, so I also added:

```
.ais-search-box--input {
height: 80% !important;
margin-top: 3px !important;
}
```

I think everything looks good now. I'll let you know if I run into anything else. Thanks again for providing this search on my site. It's much appreciated.

**Comment by pixelastic** [comment]
> But with idratherbewriting, I didn't see the same styles added (prob b/c the search integration is different),

I actually forgot to do it on idratherbewriting :)

I'm really happy with the results on all three websites! It makes discovery of content so much easier for a reader like me :tada:

**Comment by tomjoht** [comment]
Tim, I noticed that when users click a search result, if the URL doesn't go to a specific section, the URL appends `#undefined` in the URL. Is it possible to remove the `#undefined` part of the URL when the link doesn't point to a particular section?

**Comment by pixelastic** [comment]
Sure thing,

You would need to edit `_includes/search_results.html`, and change line `43` with:

```js
// Instead of
var url = `{{ site.baseurl }}${hit.url}#${hit.anchor}`;
// Replace with
var url = `{{ site.baseurl }}${hit.url}`;
if (hit.anchor) {
  url = url + '#' + hit.anchor;
}
```

This should do it :)

**Comment by tomjoht** [comment]
Thanks. That fixed the issue. I appreciate it.

**Pull request merged**
